# Generated by Django 5.0.2 on 2024-02-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_model', models.CharField(max_length=120, verbose_name='FirstName')),
                ('Platenumber', models.FloatField(blank=True)),
                ('Rentprice', models.IntegerField()),
                ('Odometer', models.FloatField(blank=True)),
                ('Year', models.IntegerField()),
                ('Condition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarDealer_FirstName', models.CharField(max_length=120, verbose_name='FirstName')),
                ('CarDealer_LastName', models.CharField(max_length=120, verbose_name='LastName')),
                ('CarDealer_MiddleName', models.CharField(max_length=120, verbose_name='MiddleName')),
                ('CarDealer_Emailadd', models.EmailField(blank=True, max_length=255, null=True)),
                ('CarDealer_Pass', models.CharField(max_length=120, verbose_name='FirstName')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_FirstName', models.CharField(max_length=120, verbose_name='FirstName')),
                ('Customer_LastName', models.CharField(max_length=120, verbose_name='LastName')),
                ('Customer_MiddleName', models.CharField(max_length=120, verbose_name='MiddleName')),
                ('Customer_LicenseNo', models.FloatField(blank=True)),
                ('Customer_Emailadd', models.EmailField(blank=True, max_length=255, null=True)),
                ('Customer_Address', models.CharField(max_length=120, verbose_name='Address')),
                ('Customer_Age', models.IntegerField()),
                ('Customer_Gender', models.CharField(max_length=32, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rental_Number', models.FloatField(blank=True)),
                ('Rental_Address', models.CharField(max_length=120, verbose_name='Address')),
                ('Date_rent', models.DateTimeField(auto_now_add=True)),
                ('Date_return', models.DateTimeField(auto_now=True)),
                ('Destination', models.TextField(blank=True, null=True)),
                ('Payment', models.IntegerField()),
            ],
        ),
    ]
