# Generated by Django 5.0.2 on 2024-02-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarDealer_FirstName', models.CharField(max_length=120, verbose_name='FirstName')),
                ('CarDealer_LastName', models.CharField(max_length=120, verbose_name='LastName')),
                ('CarDealer_MiddleName', models.CharField(max_length=120, verbose_name='MiddleName')),
                ('CarDealer_Emailadd', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address')),
                ('CarDealer_Pass', models.CharField(max_length=120, verbose_name='Password')),
            ],
        ),
        migrations.DeleteModel(
            name='Car_Dealer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_Emailadd',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address'),
        ),
    ]
